[workspace]
members = [
#  "mud-domain",
  "logs",
  "server",
#  "mud-server",
#  "mud-console",
#  "commons",
  "core",
  "core-engine",
  "mud-engine",
  "socket-server",
  "http-server",
  "mud-socket-controller",
  "core-controller",
  "mud-main",
]
