[package]
name = "mud-engine"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[dependencies]
logs = { version = "*", path = "../logs" }
commons = { version = "*", path = "../commons" }
mud-domain = { version = "*", path = "../mud-domain" }
