[package]
name = "rust-random-grid"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.0" }
getrandom = { version = "0.2.3", features = ["js"] }
rand ="0.8.0"
