[package]
name = "commons"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[lib]

[dependencies]
serde_json = "1.*"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.4"
rand_distr = "0.4.0"

