[package]
name = "socket-server"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[lib]

[dependencies]
log = "0.4.18"
env_logger = "0.10.0"
commons = { version = "*", path = "../commons" }
