[package]
name = "mud-main"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[dependencies]
logs = { version = "*", path = "../logs" }
commons = { version = "*", path = "../commons" }
mud-engine = { version = "*", path = "../mud-engine" }
socket-server = { version = "*", path = "../socket-server" }
http-server = { version = "*", path = "../http-server" }
